import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
process.env.NODE_ENV='test';
process.env.OPEN_ACCESS='false';
process.env.DATA_DIR='memory://';
process.env.ADMIN_PASSWORD='EntradaTeste123!';
delete process.env.DATABASE_URL;
const {app,db}=await import('../server.mjs');
const server=app.listen(0,'127.0.0.1');
await new Promise(resolve=>server.once('listening',resolve));
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1365,height:900}});
const requests=[];
page.on('request',request=>{if(request.url().includes('/api/'))requests.push(new URL(request.url()).pathname);});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await mkdir('test-results',{recursive:true});
try{
 await page.goto(`http://127.0.0.1:${server.address().port}`);
 await page.locator('#login-form').waitFor();
 await page.screenshot({path:'test-results/login-desktop.png',fullPage:true});
 await page.locator('[name=login]').fill('admin');
 await page.locator('[name=senha]').fill('EntradaTeste123!');
 await page.getByRole('button',{name:'Entrar na academia'}).click();
 await page.getByRole('heading',{name:'A academia, hoje.'}).waitFor();
 assert.deepEqual(requests.filter(path=>path==='/api/data'),[],'A primeira tela não deve buscar todos os cadastros');
 assert.equal(requests.filter(path=>path==='/api/overview').length,1);
 await page.locator('.nav [data-nav=aluno]').click();
 await page.getByRole('heading',{name:'Alunos'}).waitFor();
 assert.equal(requests.filter(path=>path==='/api/data').length,1,'Detalhes carregam ao abrir a área');
 await page.locator('[data-new=aluno]').click();
 await page.locator('#edit-form').waitFor();
 assert.equal(await page.locator('.form-disclosure').evaluate(el=>el.open),false);
 await page.locator('.form-disclosure summary').click();
 assert.equal(await page.locator('[name=telefone]').isVisible(),true);
 await page.locator('#close-modal').click();
 await page.setViewportSize({width:390,height:844});
 await page.locator('.menu-toggle').click();
 assert.equal(await page.locator('[data-action=logout]').isVisible(),true);
 await page.locator('[data-nav=home]').last().click();
 await page.getByRole('heading',{name:'A academia, hoje.'}).waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'test-results/dashboard-mobile-empty.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('Entrada: painel sem dados completos, carregamento sob demanda, formulário e menu mobile OK.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));await db.close();}
