import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
process.env.NODE_ENV='test';
process.env.DATA_DIR='memory://';
delete process.env.DATABASE_URL;
process.env.ADMIN_PASSWORD='AdminCadastro123!';
const {app,db}=await import('../server.mjs');
const server=app.listen(0,'127.0.0.1');
await new Promise(resolve=>server.once('listening',resolve));
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
page.setDefaultTimeout(15000);
const errors=[];page.on('pageerror',error=>errors.push(error.message));
try{
 await mkdir('test-results',{recursive:true});
 await page.goto(`http://127.0.0.1:${server.address().port}`);
 await page.locator('#login-form').waitFor();
 await page.screenshot({path:'test-results/public-login.png'});
 await page.locator('.auth-tabs').getByRole('button',{name:'Criar conta',exact:true}).click();
 await page.screenshot({path:'test-results/public-register-desktop.png'});
 await page.locator('[name=nome]').fill('Ana Silva');
 await page.locator('[name=login]').fill('ana.silva');
 await page.getByRole('button',{name:'Continuar',exact:true}).click();
 await page.locator('[name=senha]').fill('AnaSilva123!');
 await page.locator('[name=confirmacao]').fill('Diferente123!');
 await page.getByRole('button',{name:'Criar minha conta'}).click();
 await page.getByRole('alert').getByText('A confirmação não corresponde à senha.').waitFor();
 await page.getByRole('button',{name:'Mostrar senhas'}).click();
 assert.equal(await page.locator('[name=senha]').getAttribute('type'),'text');
 await page.getByRole('button',{name:'Ocultar senhas'}).click();
 await page.getByRole('button',{name:'Voltar para meus dados'}).click();
 assert.equal(await page.locator('[name=login]').inputValue(),'ana.silva');
 await page.getByRole('button',{name:'Continuar',exact:true}).click();
 await page.locator('[name=confirmacao]').fill('AnaSilva123!');
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/public-register-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.getByRole('button',{name:'Criar minha conta'}).click();
 await page.getByRole('heading',{name:'Conta criada!'}).waitFor();
 await page.getByRole('button',{name:'Voltar para o login'}).click();
 await page.locator('[name=senha]').fill('AnaSilva123!');
 await page.getByRole('button',{name:'Entrar na academia'}).click();
 await page.getByRole('alert').getByText(/aguarda aprovação/).waitFor();
 await page.locator('[name=login]').fill('admin');
 await page.locator('[name=senha]').fill('AdminCadastro123!');
 await page.getByRole('button',{name:'Entrar na academia'}).click();
 await page.getByRole('heading',{name:'Tudo pronto para um novo dia.'}).waitFor();
 await page.getByRole('button',{name:'Usuários',exact:true}).click();
 await page.getByRole('button',{name:'Aprovar acesso'}).click();
 await page.getByRole('status').getByText('Acesso aprovado.').waitFor();
 await page.getByRole('button',{name:'Fechar',exact:true}).last().click();
 await page.getByRole('button',{name:'Sair',exact:true}).click();
 await page.locator('[name=login]').fill('ana.silva');
 await page.locator('[name=senha]').fill('AnaSilva123!');
 await page.getByRole('button',{name:'Entrar na academia'}).click();
 await page.getByRole('heading',{name:'Tudo pronto para um novo dia.'}).waitFor();
 assert.equal((await db.query('SELECT aprovado FROM usuario WHERE login=$1',['ana.silva'])).rows[0].aprovado,true);
 assert.deepEqual(errors,[]);
 console.log('Cadastro público, validação, aprovação, login e layout móvel OK.');
}finally{
 await browser.close();await new Promise(resolve=>server.close(resolve));await db.close();
}
